"""add 2 default users

Revision ID: 473c3d561747
Revises: ac049d52dcfc
Create Date: 2025-06-28 14:14:45.834210

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "473c3d561747"
down_revision: Union[str, Sequence[str], None] = "ac049d52dcfc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
