"""add email and remove password

Revision ID: a3b59171f2ce
Revises: 473c3d561747
Create Date: 2025-07-22 13:25:53.705799

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "a3b59171f2ce"
down_revision: Union[str, Sequence[str], None] = "473c3d561747"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column("user", "password")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("password", sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column("user", "email")
    # ### end Alembic commands ###
