"""add email to user, mandatory field

Revision ID: 424a70a7975f
Revises: cc9e9b49c031
Create Date: 2025-10-12 12:08:25.838894

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "424a70a7975f"
down_revision: Union[str, Sequence[str], None] = "cc9e9b49c031"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column("user", sa.Column("provider", sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column("user", "password", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "password", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column("user", "provider")
    op.drop_column("user", "email")
    # ### end Alembic commands ###
